-- Domains removed; using raw SQL types instead.

-- 2. Api (data source metadata)
CREATE TABLE api (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(100) NOT NULL
);

-- 3. Location (geographic information)
CREATE TABLE location (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          region VARCHAR(100),
                          country VARCHAR(100),
                          lat DOUBLE PRECISION,
                          lon DOUBLE PRECISION,
                          timezone VARCHAR(50),
                          local_time TIMESTAMP
);

-- 4. Weather_Condition
CREATE TABLE weather_condition (
                                   code BIGINT PRIMARY KEY,
                                   text VARCHAR(255),
                                   icon VARCHAR(255)
);

-- 5. weather_fetch (renamed from Fetch)
CREATE TABLE weather_fetch (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               location_id BIGINT NOT NULL REFERENCES location(id),
                               fetch_timestamp TIMESTAMP NOT NULL,
                               api_id BIGINT NOT NULL REFERENCES api(id)
);

-- 6. RealtimeWeather
CREATE TABLE realtime_weather (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  weather_fetch_id BIGINT NOT NULL REFERENCES weather_fetch(id),
                                  last_updated_epoch BIGINT,                 -- formerly epoch_time
                                  temperature_c DOUBLE PRECISION,            -- formerly temperature_c domain
                                  condition_code BIGINT NOT NULL REFERENCES weather_condition(code),
                                  is_day BOOLEAN,
                                  wind_kph DOUBLE PRECISION,                 -- formerly wind_speed_kph domain
                                  wind_degree BIGINT,
                                  wind_direction VARCHAR(10),
                                  pressure_mb DOUBLE PRECISION,              -- formerly pressure_mb domain
                                  precipitation_mm DOUBLE PRECISION,         -- formerly precipitation_mm domain
                                  humidity DOUBLE PRECISION,                 -- formerly humidity_percentage domain
                                  cloud BIGINT,
                                  feelslike_c DOUBLE PRECISION,              -- formerly temperature_c domain
                                  windchill_c DOUBLE PRECISION,              -- formerly temperature_c domain
                                  heatindex_c DOUBLE PRECISION,              -- formerly temperature_c domain
                                  dewpoint_c DOUBLE PRECISION,               -- formerly temperature_c domain
                                  visibility_km DOUBLE PRECISION,            -- formerly visibility_km domain
                                  uv DOUBLE PRECISION,
                                  gust_kph DOUBLE PRECISION                 -- formerly wind_speed_kph domain
);

-- 7. AirQuality
CREATE TABLE air_quality (
                             realtime_weather_id BIGINT PRIMARY KEY REFERENCES realtime_weather(id),
                             co DOUBLE PRECISION,
                             no2 DOUBLE PRECISION,
                             o3 DOUBLE PRECISION,
                             so2 DOUBLE PRECISION,
                             pm2_5 DOUBLE PRECISION,
                             pm10 DOUBLE PRECISION,
                             us BIGINT,
                             gb BIGINT
);

-- 8. Forecastday
CREATE TABLE forecastday (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             weather_fetch_id BIGINT NOT NULL REFERENCES weather_fetch(id),
                             forecast_date DATE NOT NULL,
                             CONSTRAINT uq_forecastday UNIQUE (weather_fetch_id, forecast_date)
);

-- 9. Astro
CREATE TABLE astro (
                       forecastday_id BIGINT PRIMARY KEY REFERENCES forecastday(id),
                       sunrise TIME,
                       sunset TIME,
                       moonrise TIME,
                       moonset TIME,
                       moon_illumination BIGINT,
                       is_sun_up BOOLEAN,
                       is_moon_up BOOLEAN
);

-- 10. DailyForecast
CREATE TABLE daily_forecast (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                weather_fetch_id BIGINT NOT NULL REFERENCES weather_fetch(id),
                                forecastday_id BIGINT NOT NULL REFERENCES forecastday(id),
                                maxtemperature_c DOUBLE PRECISION,
                                mintemperature_c DOUBLE PRECISION,
                                avgtemperature_c DOUBLE PRECISION,
                                maxwind_kph DOUBLE PRECISION,
                                totalprecipitaton_mm DOUBLE PRECISION,
                                totalsnow_cm DOUBLE PRECISION,
                                avgvisibility_km DOUBLE PRECISION,
                                avghumidity BIGINT,
                                chance_of_rain BIGINT,
                                chance_of_snow BIGINT,
                                condition_code BIGINT NOT NULL REFERENCES weather_condition(code),
                                uv DOUBLE PRECISION
);

-- 11. HourForecast
CREATE TABLE hour_forecast (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               weather_fetch_id BIGINT NOT NULL REFERENCES weather_fetch(id),
                               forecastday_id BIGINT NOT NULL REFERENCES forecastday(id),
                               time_epoch BIGINT,                         -- formerly epoch_time domain
                               temperature_c DOUBLE PRECISION,
                               condition_code BIGINT NOT NULL REFERENCES weather_condition(code),
                               is_day BOOLEAN,
                               wind_kph DOUBLE PRECISION,
                               wind_degree BIGINT,
                               wind_direction VARCHAR(10),
                               pressure_mb DOUBLE PRECISION,
                               precipitation_mm DOUBLE PRECISION,
                               snow_cm DOUBLE PRECISION,
                               humidity DOUBLE PRECISION,
                               cloud BIGINT,
                               feelslike_c DOUBLE PRECISION,
                               windchill_c DOUBLE PRECISION,
                               heatindex_c DOUBLE PRECISION,
                               dewpoint_c DOUBLE PRECISION,
                               chance_of_rain BIGINT,
                               chance_of_snow BIGINT,
                               visibility_km DOUBLE PRECISION,
                               gust_kph DOUBLE PRECISION,
                               uv DOUBLE PRECISION
);
