server:
  port: 8080
supabase:
  api:
    url: ${SUPABASE_API_URL}
    key: ${SUPABASE_API_KEY}
api:
  weatherapi:
    name: ${API_WEATHERAPI_NAME}
    key: ${API_WEATHERAPI_KEY}
    url:
      current-weather: ${API_WEATHERAPI_URL_CURRENT_WEATHER}
      forecast: ${API_WEATHERAPI_URL_FORECAST}

spring:
  config:
    import: "file:./.env/.env.properties"
  security:
    encryption:
      password: ${SPRING_SECURITY_ENCRYPTION_PASSWORD}
      salt: ${SPRING_SECURITY_ENCRYPTION_SALT}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
